version: '3'
services:
  local-db:
    image: dy2274/hallym_dorm
    container_name: local-db
    build: ./backend/
    restart: always
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Seoul
    volumes:
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
      # - ./db/mysql/data:/var/lib/mysql
      # - ./db/mysql/init:/docker-entrypoint-initdb.d
    platform: linux/x86_64